### ISSUE TITLE
Data display sometimes includes bad time (unix epoch)

### ISSUE THREAD

**Issue by cmdcolin** [cmdcolin/travigraphjs#10]

**Comment by cmdcolin** [comment]
Could be related to network failure as it's not super reproducible

**Comment by rikukissa** [comment]
It seems it's because sometimes when you're querying new jobs that haven't finished yet, their `finished_at` field is `null`, which is probably interpreted as `0` by the graphing library

**Comment by cmdcolin** [comment]
Thanks, I'll see if i can at least filter these out!

**Comment by cmdcolin** [comment]
Should be added now
