### ISSUE TITLE
Access to private repos

### ISSUE THREAD

**Issue by adam-azarchs** [cmdcolin/travigraphjs#12]
Being able to access private repos would be great.  To do this, one needs to add the `'Authorization': 'token XXXXXXXXX'` header.  The lazy implementation would be to have a box where someone could just paste their token in (like http://edunham.github.io/travis-stats/ does).  The more advanced implementation would do a proper handshake to get the token.

**Comment by cmdcolin** [comment]
This sounds like a good idea :) I'll see if I can just add the text box, if you have resources for the handshake let me know though. I like how that other link is aware of all repos in the organization...I think this project would benefit from a few helper functions like that

**Comment by adam-azarchs** [comment]
Unfortunately documentation for how to obtain an API token programatically is lacking.  https://developer.travis-ci.com/authentication describes getting a token with their ruby-based CLI client.  That technique doesn't seem to work with GitHub 2FA enabled, however.  If they have a way of getting a token through an OAuth handshake, I can't seem to find it.

**Comment by cmdcolin** [comment]
I added a little field for doing token authorization similar to that above link, I don't have a way to test it but it should be passing along the authorization key in the header

**Comment by cmdcolin** [comment]
If you get a chance to test let me know :)

**Comment by elalemanyo** [comment]
@cmdcolin I test it and works great! Thanks!

**Comment by cmdcolin** [comment]
Nice, good to know. I'll close for now
