### ISSUE TITLE
Get Queue time

### ISSUE THREAD

**Issue by elalemanyo** [cmdcolin/travigraphjs#14]
This would be maybe also a very interesting graph, this is something that travis is already showing in insights but sure we get it prettier here.

**Comment by cmdcolin** [comment]
Could possibly use commit time compared to the started_at time as a way to estimate this

**Comment by cmdcolin** [comment]
I tested adding queue time to the site, lemme know if it works for you

**Comment by elalemanyo** [comment]
I did a pull and check it, but I can not see the queue time. Where should it appear?

**Comment by cmdcolin** [comment]
@elalemanyo you may need to clear cache

looks like this checkbox

![localhost_3000__queue=0 repo=GMOD%2Fbam-js](https://user-images.githubusercontent.com/6511937/78217459-26979a80-748a-11ea-9604-40afe3e73f52.png)

**Comment by cmdcolin** [comment]
note that this seems heavily inluenced by outliers, if you have any ideas let me know

**Comment by elalemanyo** [comment]
clear cache? sorry but how can I do this on the project?

**Comment by cmdcolin** [comment]
I was using something called lscache that cached across refresh using localstorage but I think it caused more trouble than it helped. Now you can just visit it and see if it might work

**Comment by cmdcolin** [comment]
I removed the lscache

**Comment by elalemanyo** [comment]
No it works great!

**Comment by cmdcolin** [comment]
Awesome! Let me know if there's anything else . Currious if it matches the Travis ci native widget for queue time
