### ISSUE TITLE
Get info when scrolling on dots?

### ISSUE THREAD

**Issue by shouldsee** [cmdcolin/travigraphjs#16]
e.g. would like to know which build was the first one that caused a change in build time.

**Comment by cmdcolin** [comment]
this was available at one point but lost in the transition to react recently

**Comment by shouldsee** [comment]
> this was available at one point but lost in the transition to react recently

huh, technologies

**Comment by cmdcolin** [comment]
yep. I'd be happy to add this back though....I'll see what I can do

**Comment by cmdcolin** [comment]
@shouldsee it should be added at https://cmdcolin.github.io/travigraphjs/ now

**Comment by cmdcolin** [comment]
try to clear cache also because it adds some more stuff to the cache

**Comment by shouldsee** [comment]
Ah thanks it is working! You are a blazing fast star!

------
Though the box disappear so fast that I could not copy any info from it... This is super useful already but more hyperlinks will be helpful!!

**Comment by cmdcolin** [comment]
Right, I was looking into if I can make the tooltip delay going away but it was difficult to see if there was an option with the library vega.

 I could maybe make a click action open a little info area where things could be copied from

**Comment by cmdcolin** [comment]
I have an onclick handler now, feel free to check it out :)

**Comment by cmdcolin** [comment]
Let me know if you have any other requests

**Comment by shouldsee** [comment]
Just checked. It was smooth as silk thanks!
