### ISSUE TITLE
Improvements to picking start and end build numbers

### ISSUE THREAD

**Issue by rmzelle** [cmdcolin/travigraphjs#4]
I really enjoyed your visualization tool! Very useful.

For picking the range of build numbers, a few possible improvements:

* It would be nice if the tool would automatically prefill the end build number by checking the most recent build of the selected repository. (build numbers are mentioned at https://travis-ci.org/citation-style-language/styles/builds, but I'm not sure if it's easy to get the most recent build number via the API)
* Also, would it be possible to have the script stop automatically once there are no more builds? I accidentally added an extra zero to the end build number (120000 instead of 12000), and the script just kept going.
* Maybe you could change "Simply enter ... the start and end build numbers (use 0 and a semi-large number to get whole history, total build numbers is not known beforehand)" to something like "Simply enter ... the start and end build numbers (check the Travis webpage for your repository for the build number of the most recent build)"?
* It looks like build numbers start at 1, not 0. See e.g. the bottom of the page at https://travis-ci.org/citation-style-language/Sheldon/builds

![image](https://user-images.githubusercontent.com/77951/38207863-28171a22-367d-11e8-8923-284c107026c3.png)
https://cmdcolin.github.io/travigraphjs/?repo=citation-style-language/styles&start=0&end=12000

**Comment by cmdcolin** [comment]
Thanks!
I definitely agree having it auto detect last build is worthwhile, I will look into this. That would address several usability issues:)

**Comment by cmdcolin** [comment]
I added a couple improvements on latest release! See website for update

Changes:

- Checks for existence of repo and total number of builds on submit. It doesn't automatically update the start or end fields but I'd be interested if there's a nice workflow that might do that. But, given that it just returns last build, can just copy and paste into field.
- Uses travis-ci api v3 (which also distinguishes passed and succeeded)

Note: It also doesn't tell you when the builds are returning nothing if you add an extra 0 (reason is it just keeps making requests and combines results at end, so it doesn't "peek"" in the middle of making results to see if it's done)

Anyways, check it out and let me know

**Comment by cmdcolin** [comment]
I made a couple changes that hopefully improve the usability a bit. Not all issues you addressed are fixed but I hope it is helpful. 

Feel free to reopen a new issue if you find that any of those issues need priority fixes :)

**Comment by rmzelle** [comment]
Great, thanks!

**Comment by rmzelle** [comment]
> Checks for existence of repo and total number of builds on submit. It doesn't automatically update the start or end fields but I'd be interested if there's a nice workflow that might do that. But, given that it just returns last build, can just copy and paste into field.

The tool is great as is, but just some more thoughts:

* People are probably most interested in the most recent builds. Instead of specifying start and end build numbers, you could also allow the user to specify how many builds to plot, going backward (e.g. 500 most recent, 1000 most recent, or all builds). Even nicer would be if you could select dates instead of build numbers (e.g. last 90 days, last 180 days, last year, whole history).
* With the current setup, it would be nice if the "Total number of builds" number was automatically retrieved before pressing Submit. You could e.g. put in a delay (300 ms or so), so that when the user is done typing the organization/repo name the number gets retrieved.

**Comment by cmdcolin** [comment]
Thanks a ton for the ideas :)

I made some new issues here to try and keep track

https://github.com/cmdcolin/travigraphjs/issues/8
https://github.com/cmdcolin/travigraphjs/issues/7


Feel free to add more ideas about dashboard style view. I feel like more can be done on the data viz side that the scatterplot doesn't even capture, if you have ideas let me know

**Comment by cmdcolin** [comment]
There is now a lookup button to populate the total builds and last N builds and a linked graph to zoom in on data :)
