### ISSUE TITLE
travis-ci.com support

### ISSUE THREAD

**Issue by PatMyron** [cmdcolin/travigraphjs#9]
It looks like `.org` is being deprecated in favor of `.com` soon:
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
`Over the next several months, we’ll be migrating all travis-ci.org repositories and customers to travis-ci.com`

I think these endpoints would need to be un-hardcoded:

https://github.com/cmdcolin/travigraphjs/blob/f9eda2c80b18123da526c7c35333c45faeb8544b/src/index.js#L98

https://github.com/cmdcolin/travigraphjs/blob/f9eda2c80b18123da526c7c35333c45faeb8544b/src/index.js#L129

**Comment by cmdcolin** [comment]
Thanks I'll check out. In actually this repo needs a bunch of work probably!

**Comment by cmdcolin** [comment]
Took awhile but got some motivation and rewrote the app in react.js, with this feature added :)

**Comment by cmdcolin** [comment]
It needs a couple improvements such as a better loading progress indicator but I think the code is much nicer now

**Comment by cmdcolin** [comment]
Progress indicator done
